### ISSUE TITLE
Please consider using "traitsui.editors.api" instead of "traitsui.editors" to import editor factories

### ISSUE THREAD

**Issue by rahulporuri** [KBIbiopharma/pybleau#201]
https://github.com/KBIbiopharma/pybleau/blob/1768c97dd5f2e9f563d4e28fa25941ed66b3ad72/pybleau/app/ui/filter_expression_editor.py#L12

Ref https://github.com/enthought/traitsui/issues/1617

**Comment by jonathanrocher** [comment]
Thank you for the heads up @rahulporuri ! Really appreciate it!
